Repository ToposInstitute/CatColab, pull requests merged in 2025-05, with the labels that each got.

#490 Fix cut and paste errors in backups config
  infrastructure/modules/backup.nix
Labels: backend

#492 Fixes to Nix config for production deployment
  flake.nix
  infrastructure/hosts/catcolab-jmoggr/default.nix
  infrastructure/hosts/catcolab-next/default.nix
  infrastructure/hosts/catcolab/default.nix
  infrastructure/modules/backend.nix
  infrastructure/modules/backup.nix
  infrastructure/secrets/secrets.nix
  packages/automerge-doc-server/default.nix
Labels: bug, backend

#494 Stock-flow visualization: Larger boxes, ortho flows, and blue links
  packages/frontend/src/stdlib/analyses/graph_visualization.css
  packages/frontend/src/stdlib/analyses/stock_flow_diagram.tsx
Labels: enhancement, frontend, visualization

#495 Upgrade from `tsify_next` back to `tsify`
  Cargo.lock
  packages/catlog-wasm/Cargo.toml
  packages/catlog-wasm/src/analyses.rs
  packages/catlog-wasm/src/model.rs
  packages/catlog-wasm/src/model_diagram.rs
  packages/catlog-wasm/src/model_morphism.rs
  packages/catlog-wasm/src/result.rs
  packages/catlog-wasm/src/theory.rs
  packages/catlog/Cargo.toml
  packages/catlog/src/dbl/category.rs
  packages/catlog/src/dbl/model.rs
  packages/catlog/src/dbl/model_diagram.rs
  packages/catlog/src/dbl/model_morphism.rs
  packages/catlog/src/one/path.rs
  packages/catlog/src/stdlib/analyses/ode/lotka_volterra.rs
  packages/catlog/src/stdlib/analyses/ode/mass_action.rs
  packages/catlog/src/stdlib/analyses/ode/mod.rs
Labels: frontend, core

#496 Well-typing predicate in egglog theory of categories
  packages/catlog/src/egglog_util.rs
  packages/catlog/src/one/fp_category.rs
Labels: enhancement, core

#498 Linked to an analysis instead of a model
  packages/frontend/src/help/theory/reg-net.mdx
Labels: bug, documentation

#429 Rename AlgebraicJuliaService to CatColabInterop and refactor
  .gitignore
  packages/algjulia-interop/.gitignore
  packages/algjulia-interop/Project.toml
  packages/algjulia-interop/README.md
  packages/algjulia-interop/jupyter_server.sh
  packages/algjulia-interop/make_sysimage.jl
  packages/algjulia-interop/src/CatColabInterop.jl
  packages/algjulia-interop/src/decapodes-service/DecapodesService.jl
  packages/algjulia-interop/src/decapodes-service/analysis/Analysis.jl
  packages/algjulia-interop/src/decapodes-service/analysis/initial_conditions.jl
  packages/algjulia-interop/src/decapodes-service/analysis/ns_helper.jl
  packages/algjulia-interop/src/decapodes-service/analysis/simulation.jl
  packages/algjulia-interop/src/decapodes-service/diagram.jl
  packages/algjulia-interop/src/decapodes-service/geometry.jl
  packages/algjulia-interop/src/decapodes-service/model.jl
  packages/algjulia-interop/src/kernel_support.jl
  packages/algjulia-interop/sysimage_precompile.jl
  packages/algjulia-interop/test/Project.toml
  packages/algjulia-interop/test/runtests.jl
  packages/algjulia-interop/test/test_jsons/diagrams/diffusivity_constant/analysis.json
  packages/algjulia-interop/test/test_jsons/diagrams/diffusivity_constant/diagram.json
  packages/algjulia-interop/test/test_jsons/diagrams/inverse_laplacian/analysis.json
  packages/algjulia-interop/test/test_jsons/diagrams/inverse_laplacian/diagram.json
  packages/algjulia-interop/test/test_jsons/diagrams/inverse_laplacian_longtrip/analysis.json
  packages/algjulia-interop/test/test_jsons/diagrams/inverse_laplacian_longtrip/diagram.json
  packages/algjulia-interop/test/test_jsons/diagrams/ns_vort/analysis.json
  packages/algjulia-interop/test/test_jsons/diagrams/ns_vort/diagram.json
  packages/algjulia-interop/test/test_jsons/diffconst_payload1.json
  packages/algjulia-interop/test/test_jsons/models/model_dec.json
  packages/algjulia-interop/test/test_jsons/models/model_dec_scalar.json
  packages/algjulia-interop/test/test_jsons/payload.json
  packages/algjulia-service/jupyter_server.sh
  packages/algjulia-service/src/decapodes-service/diagram.jl
  packages/algjulia-service/sysimage_precompile.jl
  packages/algjulia-service/test/runtests.jl
  packages/algjulia-service/test/test_jsons/diffusion_data.json
  packages/algjulia-service/test/test_jsons/diffusion_data_twovars.json
  packages/algjulia-service/test/test_jsons/diffusion_long_trip.json
  packages/algjulia-service/test/test_jsons/diffusivity_constant.json
  packages/algjulia-service/test/test_jsons/example.json
  packages/algjulia-service/test/test_jsons/ns_vorticity.json
  packages/frontend/src/stdlib/analyses/decapodes.tsx
Labels: external

#464 Document breadcrumbs
  packages/frontend/src/analysis/analysis_editor.tsx
  packages/frontend/src/diagram/diagram_editor.tsx
  packages/frontend/src/index.css
  packages/frontend/src/model/model_editor.tsx
  packages/frontend/src/page/document_breadcrumbs.css
  packages/frontend/src/page/document_breadcrumbs.tsx
  packages/frontend/src/page/index.ts
Labels: enhancement, frontend, ui/ux

#473 Refactor frontend-core interface to process notebooks in Rust
  Cargo.lock
  Cargo.toml
  packages/catlog-wasm/Cargo.toml
  packages/catlog-wasm/src/model.rs
  packages/catlog-wasm/src/model_diagram.rs
  packages/frontend/package.json
  packages/frontend/pnpm-lock.yaml
  packages/frontend/src/analysis/document.ts
  packages/frontend/src/api/document.ts
  packages/frontend/src/diagram/diagram_editor.tsx
  packages/frontend/src/diagram/document.ts
  packages/frontend/src/diagram/types.ts
  packages/frontend/src/model/document.ts
  packages/frontend/src/model/index.ts
  packages/frontend/src/model/model_editor.tsx
  packages/frontend/src/model/types.ts
  packages/frontend/src/notebook/notebook_editor.tsx
  packages/frontend/src/notebook/types.ts
  packages/frontend/src/stdlib/analyses/decapodes.tsx
  packages/frontend/src/stdlib/analyses/model_graph.tsx
  packages/frontend/src/stdlib/analyses/stock_flow_diagram.tsx
  packages/frontend/src/util/types.ts
  packages/frontend/src/visualization/export_svg.ts
  packages/notebook-types/Cargo.toml
  packages/notebook-types/README.md
  packages/notebook-types/examples/v0/An Example Instance.json
  packages/notebook-types/examples/v0/CA Cap-and-trade.json
  packages/notebook-types/examples/v0/SEIRV.json
  packages/notebook-types/examples/v0/Sustainable Peace.json
  packages/notebook-types/examples/v0/The Ontology of CatColab.json
  packages/notebook-types/src/lib.rs
  packages/notebook-types/src/v0/analysis.rs
  packages/notebook-types/src/v0/api.rs
  packages/notebook-types/src/v0/cell.rs
  packages/notebook-types/src/v0/diagram_judgment.rs
  packages/notebook-types/src/v0/document.rs
  packages/notebook-types/src/v0/mod.rs
  packages/notebook-types/src/v0/model.rs
  packages/notebook-types/src/v0/model_judgment.rs
  packages/notebook-types/src/v0/notebook.rs
  packages/notebook-types/src/v0/path.rs
  packages/notebook-types/src/v0/theory.rs
Labels: frontend, core, strategic

#505 Pin rust toolchain version used in CI
  .github/workflows/ci.yml
Labels: core, backend

#509 Upgrade Rust to 1.87.0
  flake.nix
  packages/catlog/src/zero/column.rs
  rust-toolchain.toml
Labels: core, backend

#513 Add `lld` to Nix dev shell
  flake.nix
Labels: frontend

#510 Use sqlx_migrator for migrations
  Cargo.lock
  Cargo.nix
  Cargo.toml
  infrastructure/modules/backend.nix
  packages/backend/README.md
  packages/backend/default.nix
  packages/backend/migrations/20241004010448_document_refs.down.sql
  packages/backend/migrations/20241004010448_document_refs.up.sql
  packages/backend/migrations/20241025030906_users.down.sql
  packages/backend/migrations/20241025030906_users.up.sql
  packages/backend/migrations/20250409171833_add_permissions_object_subject_idx.down.sql
  packages/backend/migrations/20250409171833_add_permissions_object_subject_idx.up.sql
  packages/migrator/Cargo.toml
  packages/migrator/README.md
  packages/migrator/default.nix
  packages/migrator/src/main.rs
  packages/migrator/src/migrations/m20241004010448_document_refs.rs
  packages/migrator/src/migrations/m20241025030906_users.rs
  packages/migrator/src/migrations/m20250409171833_add_permissions_object_subject_idx.rs
  packages/migrator/src/migrations/mod.rs
Labels: enhancement, backend

#516 Add `db-utils` script for database development
  .gitignore
  flake.nix
  infrastructure/scripts/db-utils
  infrastructure/scripts/db-utils-lib.sh
Labels: enhancement, backend

#517 FIX: pass custom `rustToolchain` to migrator package
  Cargo.nix
  infrastructure/modules/backend.nix
  packages/migrator/default.nix
Labels: bug, backend

#520 Add `rclone.conf` to be used for backup service on next
  infrastructure/hosts/catcolab-next/default.nix
  infrastructure/hosts/catcolab/default.nix
  infrastructure/secrets/rclone.conf.next.age
  infrastructure/secrets/rclone.conf.prod.age
  infrastructure/secrets/secrets.nix
Labels: backend

#518 Fix paths in backupdb script and add option for different envs
  infrastructure/hosts/catcolab-next/default.nix
  infrastructure/hosts/catcolab/default.nix
  infrastructure/modules/backup.nix
Labels: bug, backend

#519 Run backupd script at end of deploys to act as a canary for the backup timer
  infrastructure/modules/backup.nix
Labels: enhancement, backend

#522 Add `--clean` argument to `pg_dump` for database backups
  infrastructure/modules/backup.nix
Labels: enhancement, backend

#446 Automerge storage adapter for Postgres DB
  packages/automerge-doc-server/src/main.ts
  packages/automerge-doc-server/src/migrations/index.ts
  packages/automerge-doc-server/src/migrations/m20250516154702_automerge_storage.ts
  packages/automerge-doc-server/src/postgres_storage_adapter.test.ts
  packages/automerge-doc-server/src/postgres_storage_adapter.ts
  packages/automerge-doc-server/src/server.ts
  packages/automerge-doc-server/src/socket.ts
  packages/automerge-doc-server/src/types.ts
  packages/backend/.sqlx/query-05183554f0c9207cdd1e89a948d3da5238ede1773a9507446694e9f7b4d2b16c.json
  packages/backend/.sqlx/query-4a6e4d9b1b5297262cd397cadcf50f18096bc3a289d643a031091bdba0243a2c.json
  packages/backend/.sqlx/query-6425b7d75c5fd6482701adba8011472860299d4fc872194449e18682cfed5bab.json
  packages/backend/.sqlx/query-826fe6b1579d889b2127ea34cfa8e7c8ab05b6f2d057d33e4a27e263e89659a1.json
  packages/backend/.sqlx/query-a8cb9f26893bbf784cf8a71090e64c3603e238ea6786d327f64ae04aef205198.json
  packages/backend/src/app.rs
  packages/backend/src/document.rs
  packages/backend/src/rpc.rs
  packages/migrator/src/migrations/m20250516154702_automerge_storage.rs
  packages/migrator/src/migrations/mod.rs
Labels: enhancement, backend, strategic

#528 FIX: add missing deps to automerge-doc-server
  packages/automerge-doc-server/README.md
  packages/automerge-doc-server/default.nix
  packages/automerge-doc-server/package.json
  packages/automerge-doc-server/pnpm-lock.yaml
Labels: bug, backend

#530 FIX: make automerge-doc-server standalone so it can be invoked by the migrator tool
  infrastructure/modules/backend.nix
  packages/automerge-doc-server/default.nix
Labels: bug, backend
