Repository ToposInstitute/CatColab, pull requests merged in 2025-06, with the labels that each got.

#534 FIX: add missing catcolab secrets to automerge service
  infrastructure/modules/backend.nix
Labels: bug, backend

#548 Update to Rust v1.88
  flake.nix
  packages/backend/src/auth.rs
  packages/backend/src/main.rs
  packages/catlog-wasm/src/model.rs
  packages/catlog-wasm/src/theories.rs
  packages/catlog-wasm/src/theory.rs
  packages/catlog/src/egglog_util.rs
  packages/catlog/src/simulate/ode/polynomial.rs
  packages/catlog/src/zero/rig.rs
  packages/migrator/README.md
  rust-toolchain.toml
Labels: core

#551 Functors between finitely presented categories
  packages/catlog-wasm/src/model_diagram.rs
  packages/catlog/src/dbl/model.rs
  packages/catlog/src/dbl/model_diagram.rs
  packages/catlog/src/dbl/model_morphism.rs
  packages/catlog/src/dbl/theory.rs
  packages/catlog/src/one/category.rs
  packages/catlog/src/one/fp_category.rs
  packages/catlog/src/one/functor.rs
  packages/catlog/src/one/graph.rs
  packages/catlog/src/one/mod.rs
  packages/catlog/src/refs.rs
  packages/catlog/src/zero/column.rs
Labels: enhancement, core

#552 Pushforward migration of models of discrete double theories
  packages/catlog-wasm/src/model_diagram.rs
  packages/catlog/src/dbl/model.rs
  packages/catlog/src/dbl/model_diagram.rs
  packages/catlog/src/dbl/model_morphism.rs
  packages/catlog/src/dbl/theory.rs
  packages/catlog/src/one/functor.rs
  packages/catlog/src/one/graph.rs
  packages/catlog/src/zero/column.rs
Labels: enhancement, core
