Repository ToposInstitute/CatColab, pull requests merged in 2025-03, with the labels that each got.

#436 Add Jason's ssh public key to catcolab-next
  infrastructure/hosts/catcolab-next/default.nix
  infrastructure/secrets/secrets.nix
Labels: backend

#441 Refactor double theories to use virtual double categories
  packages/catlog-wasm/src/theory.rs
  packages/catlog/src/dbl/category.rs
  packages/catlog/src/dbl/mod.rs
  packages/catlog/src/dbl/model.rs
  packages/catlog/src/dbl/theory.rs
  packages/catlog/src/dbl/theory_next.rs
  packages/catlog/src/dbl/tree.rs
  packages/catlog/src/one/path.rs
Labels: enhancement, core

#442 Operad structure on double trees
  packages/catlog/src/dbl/mod.rs
  packages/catlog/src/dbl/tree.rs
  packages/catlog/src/dbl/tree_algorithms.rs
Labels: enhancement, core

#449 The VDC freely generated by a virtual double graph
  packages/catlog/src/dbl/category.rs
  packages/catlog/src/dbl/tree.rs
  packages/catlog/src/dbl/tree_algorithms.rs
Labels: enhancement, core

#450 Automate the deployment of the backend for catcolab-next
  .github/workflows/deploy.yml
  infrastructure/hosts/catcolab-next/backend.nix
Labels: enhancement, backend

#460 Remove `vite-plugin-top-level-await` to fix source maps
  packages/frontend/package.json
  packages/frontend/pnpm-lock.yaml
  packages/frontend/vite.config.ts
Labels: bug, frontend
