Repository ToposInstitute/CatColab, pull requests merged in 2025-08, with the labels that each got.

#616 Split frontend theories into individual files
  packages/frontend/src/App.tsx
  packages/frontend/src/diagram/diagram_editor.tsx
  packages/frontend/src/diagram/morphism_cell_editor.tsx
  packages/frontend/src/diagram/object_cell_editor.tsx
  packages/frontend/src/help/logic_help_detail.tsx
  packages/frontend/src/model/document.ts
  packages/frontend/src/model/model_editor.tsx
  packages/frontend/src/model/morphism_cell_editor.tsx
  packages/frontend/src/model/object_cell_editor.tsx
  packages/frontend/src/model/object_input.tsx
  packages/frontend/src/page/document_menu.tsx
  packages/frontend/src/page/menubar.tsx
  packages/frontend/src/page/toolbar.tsx
  packages/frontend/src/stdlib/analyses/diagram_graph.tsx
  packages/frontend/src/stdlib/analyses/model_graph.tsx
  packages/frontend/src/stdlib/analyses/stock_flow_diagram.tsx
  packages/frontend/src/stdlib/theories.ts
  packages/frontend/src/stdlib/theories.tsx
  packages/frontend/src/stdlib/theories/causal-loop-delays.ts
  packages/frontend/src/stdlib/theories/causal-loop.ts
  packages/frontend/src/stdlib/theories/empty.ts
  packages/frontend/src/stdlib/theories/indeterminate-causal-loop.ts
  packages/frontend/src/stdlib/theories/petri-net.ts
  packages/frontend/src/stdlib/theories/primitive-stock-flow.ts
  packages/frontend/src/stdlib/theories/reg-net.ts
  packages/frontend/src/stdlib/theories/simple-olog.ts
  packages/frontend/src/stdlib/theories/simple-schema.ts
  packages/frontend/src/stdlib/theories/unary-dec.ts
  packages/frontend/src/stdlib/types.ts
Labels: frontend

#653 Major version increase for automerge, automerge-repo, and automerge-prosemirror
  packages/automerge-doc-server/package.json
  packages/automerge-doc-server/pnpm-lock.yaml
  packages/automerge-doc-server/src/server.ts
  packages/frontend/package.json
  packages/frontend/pnpm-lock.yaml
  packages/frontend/src/api/document.ts
  packages/frontend/src/api/document_rpc.test.ts
  packages/frontend/src/components/rich_text_editor/basic_schema.ts
  packages/frontend/src/components/rich_text_editor/schema.ts
Labels: frontend, backend

#659 Don't automatically focus the first cell in a notebook
  packages/frontend/src/notebook/notebook_editor.tsx
Labels: bug, ui/ux

#660 Push forward models along general maps in frontend
  packages/catlog-wasm/package.json
  packages/catlog-wasm/src/model.rs
  packages/catlog-wasm/src/model_morphism.rs
  packages/catlog-wasm/src/theories.rs
  packages/catlog-wasm/src/theory.rs
  packages/catlog/src/dbl/discrete/model.rs
  packages/catlog/src/dbl/discrete/model_morphism.rs
  packages/catlog/src/dbl/discrete/theory.rs
  packages/catlog/src/one/functor.rs
  packages/catlog/src/stdlib/mod.rs
  packages/catlog/src/stdlib/theories.rs
  packages/catlog/src/stdlib/theory_morphisms.rs
  packages/catlog/src/zero/column.rs
  packages/frontend/package.json
  packages/frontend/pnpm-lock.yaml
  packages/frontend/src/diagram/document.ts
  packages/frontend/src/model/document.ts
  packages/frontend/src/model/model_editor.tsx
  packages/frontend/src/notebook/types.ts
  packages/frontend/src/stdlib/theories/causal-loop-delays.ts
  packages/frontend/src/stdlib/theories/causal-loop.ts
  packages/frontend/src/stdlib/theories/empty.ts
  packages/frontend/src/stdlib/theories/indeterminate-causal-loop.ts
  packages/frontend/src/stdlib/theories/petri-net.ts
  packages/frontend/src/stdlib/theories/primitive-stock-flow.ts
  packages/frontend/src/stdlib/theories/reg-net.ts
  packages/frontend/src/stdlib/theories/simple-olog.ts
  packages/frontend/src/stdlib/theories/simple-schema.ts
  packages/frontend/src/stdlib/theories/unary-dec.ts
  packages/frontend/src/theory/types.ts
Labels: enhancement, frontend

#668 Pass the correct environment file to backup service
  infrastructure/modules/catcolab/backup.nix
Labels: bug, backend

#633 Math docs for modal double theories
  math-docs/trees/macros.tree
  math-docs/trees/mat-0001.tree
  math-docs/trees/mdt-0001.tree
  math-docs/trees/mdt-0002.tree
  math-docs/trees/mdt-0003.tree
  math-docs/trees/mdt-0004.tree
  math-docs/trees/mdt-0005.tree
  math-docs/trees/mdt-0006.tree
  math-docs/trees/mdt-0007.tree
  math-docs/trees/mdt-0008.tree
  math-docs/trees/refs/shulman-2016.tree
Labels: documentation, math

#687 Fix poor performance of Jupyter kernels in the frontend
  flake.nix
  packages/algjulia-interop/jupyter_server.sh
  packages/algjulia-interop/src/kernel_support.jl
  packages/frontend/src/stdlib/analyses/decapodes.tsx
  packages/frontend/src/stdlib/analyses/jupyter.ts
Labels: external, performance

#694 Fix duplicated/missing TS type defs for `notebook-types`
  packages/catlog-wasm/src/lib.rs
  packages/notebook-types/Cargo.toml
  packages/notebook-types/src/lib.rs
  packages/notebook-types/src/v0/document.rs
Labels: bug, frontend

#697 Avoid use of `NonEmpty` in `notebook-types`
  Cargo.lock
  packages/catlog-wasm/src/model.rs
  packages/notebook-types/Cargo.toml
  packages/notebook-types/src/lib.rs
  packages/notebook-types/src/v0/path.rs
Labels: frontend

#699 Introduce a single type `QualifiedName` for all IDs
  packages/catlog-wasm/src/analyses.rs
  packages/catlog-wasm/src/model.rs
  packages/catlog-wasm/src/model_diagram.rs
  packages/catlog-wasm/src/model_morphism.rs
  packages/catlog-wasm/src/theories.rs
  packages/catlog-wasm/src/theory.rs
  packages/catlog/Cargo.toml
  packages/catlog/src/dbl/discrete/model.rs
  packages/catlog/src/dbl/discrete/model_diagram.rs
  packages/catlog/src/dbl/discrete/model_morphism.rs
  packages/catlog/src/dbl/discrete/theory.rs
  packages/catlog/src/dbl/discrete_tabulator/model.rs
  packages/catlog/src/dbl/discrete_tabulator/theory.rs
  packages/catlog/src/dbl/modal/model.rs
  packages/catlog/src/dbl/modal/theory.rs
  packages/catlog/src/dbl/model.rs
  packages/catlog/src/dbl/theory.rs
  packages/catlog/src/one/fp_category.rs
  packages/catlog/src/one/functor.rs
  packages/catlog/src/one/path.rs
  packages/catlog/src/stdlib/analyses/ode/linear_ode.rs
  packages/catlog/src/stdlib/analyses/ode/lotka_volterra.rs
  packages/catlog/src/stdlib/analyses/ode/mass_action.rs
  packages/catlog/src/stdlib/analyses/ode/mod.rs
  packages/catlog/src/stdlib/models.rs
  packages/catlog/src/stdlib/theories.rs
  packages/catlog/src/stdlib/theory_morphisms.rs
  packages/catlog/src/zero/mod.rs
  packages/catlog/src/zero/qualified_name.rs
  packages/frontend/src/stdlib/analyses/linear_ode.tsx
  packages/frontend/src/stdlib/analyses/lotka_volterra.tsx
  packages/frontend/src/stdlib/analyses/mass_action.tsx
  packages/notebook-types/src/v0/model.rs
Labels: frontend, core

#695 Replace Jupyter server bash script with Julia code
  packages/algjulia-interop/.gitignore
  packages/algjulia-interop/Project.toml
  packages/algjulia-interop/README.md
  packages/algjulia-interop/ext/SysImageExt.jl
  packages/algjulia-interop/jupyter_server.sh
  packages/algjulia-interop/src/CatColabInterop.jl
  packages/algjulia-interop/src/run_jupyter.jl
  packages/algjulia-interop/test/runtests.jl
Labels: enhancement, external

#704 Fixes and QoL improvements for CatColabInterop kernel management
  packages/algjulia-interop/src/CatColabInterop.jl
  packages/algjulia-interop/src/kernel_management.jl
  packages/algjulia-interop/src/result.jl
  packages/frontend/src/stdlib/analyses/decapodes.tsx
Labels: bug, enhancement, external

#702 Use elaborated model in analyses and store ID-label mapping in Rust
  packages/catlog-wasm/src/model.rs
  packages/catlog-wasm/src/model_diagram.rs
  packages/catlog-wasm/src/model_morphism.rs
  packages/catlog-wasm/src/theories.rs
  packages/catlog-wasm/src/theory.rs
  packages/catlog/src/dbl/discrete/model_morphism.rs
  packages/catlog/src/zero/mod.rs
  packages/catlog/src/zero/qualified.rs
  packages/catlog/src/zero/qualified_name.rs
  packages/frontend/src/components/id_input.tsx
  packages/frontend/src/diagram/document.ts
  packages/frontend/src/diagram/object_input.tsx
  packages/frontend/src/diagram/types.ts
  packages/frontend/src/model/document.ts
  packages/frontend/src/model/morphism_input.tsx
  packages/frontend/src/model/object_input.tsx
  packages/frontend/src/model/object_list_editor.tsx
  packages/frontend/src/model/types.ts
  packages/frontend/src/stdlib/analyses/decapodes.tsx
  packages/frontend/src/stdlib/analyses/diagram_graph.tsx
  packages/frontend/src/stdlib/analyses/linear_ode.tsx
  packages/frontend/src/stdlib/analyses/lotka_volterra.tsx
  packages/frontend/src/stdlib/analyses/mass_action.tsx
  packages/frontend/src/stdlib/analyses/model_graph.tsx
  packages/frontend/src/stdlib/analyses/petri_net_visualization.tsx
  packages/frontend/src/stdlib/analyses/simulation.ts
  packages/frontend/src/stdlib/analyses/stock_flow_diagram.tsx
  packages/frontend/src/stdlib/analyses/submodel_graphs.tsx
  packages/frontend/src/stdlib/theories/primitive-stock-flow.ts
  packages/frontend/src/util/indexing.ts
Labels: enhancement, frontend, core
