Repository ToposInstitute/CatColab, pull requests merged in 2025-04, with the labels that each got.

#461 Pull CatColab from ToposInstitute and deploy current hosts configuration
  infrastructure/modules/host.nix
Labels: bug, backend

#462 Remove deployuser script and run build commands over ssh
  .github/workflows/deploy.yml
  infrastructure/modules/host.nix
Labels: backend

#453 Universal property of composites in VDCs
  packages/catlog/src/dbl/category.rs
  packages/catlog/src/dbl/theory.rs
  packages/catlog/src/one/path.rs
Labels: enhancement, core

#459 Log users out if their session is stale
  packages/backend/.sqlx/query-3645a86b3df08de865372b02d588272bb950744a38d46079ca18b11e405058a3.json
  packages/backend/pkg/src/index.ts
  packages/backend/src/auth.rs
  packages/backend/src/document.rs
  packages/backend/src/rpc.rs
  packages/frontend/src/App.tsx
Labels: bug, enhancement, frontend, backend

#465 Add backend for quering refs and a documents page
  Cargo.lock
  Cargo.nix
  README.md
  flake.nix
  packages/backend/.sqlx/query-93fae80274a3a31501e6f15dee038593f69a227d962a5c498a60786f3bb4b299.json
  packages/backend/Cargo.toml
  packages/backend/README.md
  packages/backend/migrations/20250409171833_add_permissions_object_subject_idx.down.sql
  packages/backend/migrations/20250409171833_add_permissions_object_subject_idx.up.sql
  packages/backend/pkg/src/RefQueryParams.ts
  packages/backend/pkg/src/RefStub.ts
  packages/backend/pkg/src/index.ts
  packages/backend/src/document.rs
  packages/backend/src/rpc.rs
  packages/frontend/src/App.tsx
  packages/frontend/src/api/document_rpc.test.ts
  packages/frontend/src/api/rpc.ts
  packages/frontend/src/api/user_rpc.test.ts
  packages/frontend/src/page/menubar.tsx
  packages/frontend/src/user/documents.css
  packages/frontend/src/user/documents.tsx
  packages/frontend/src/util/test_util.ts
Labels: enhancement, frontend, backend

#471 Refactor double trees to use new data structure for open trees
  Cargo.lock
  packages/catlog/Cargo.toml
  packages/catlog/src/dbl/category.rs
  packages/catlog/src/dbl/mod.rs
  packages/catlog/src/dbl/model_diagram.rs
  packages/catlog/src/dbl/theory.rs
  packages/catlog/src/dbl/tree.rs
  packages/catlog/src/one/mod.rs
  packages/catlog/src/one/path.rs
  packages/catlog/src/one/tree.rs
  packages/catlog/src/one/tree_algorithms.rs
  packages/catlog/src/refs.rs
Labels: core

#479 Support for Darwin devShell in flake.nix
  flake.lock
  flake.nix
Labels: backend

#483 Fix firebase JWT keys not being refreshed
  packages/backend/src/main.rs
Labels: bug, backend

#486 Filter logs using level from RUST_LOG is available
  Cargo.lock
  Cargo.nix
  packages/backend/Cargo.toml
  packages/backend/src/main.rs
Labels: backend

#487 Generate numeric IDs for egglog rather coercing to symbols
  packages/catlog-wasm/Cargo.toml
  packages/catlog-wasm/src/model_morphism.rs
  packages/catlog/Cargo.toml
  packages/catlog/src/dbl/model.rs
  packages/catlog/src/dbl/model_diagram.rs
  packages/catlog/src/dbl/model_morphism.rs
  packages/catlog/src/egglog_util.rs
  packages/catlog/src/one/fp_category.rs
  packages/catlog/src/stdlib/analyses/ode/lotka_volterra.rs
Labels: core

#488 Use nix to install fswatch and the full TeXLive distribution
  dev-docs/.envrc
  dev-docs/serve.sh
  dev-docs/shell.nix
  dev-docs/watch.sh
Labels: documentation
